version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./jenkins.yaml:/var/jenkins_home/casc_configs/jenkins.yaml
      - ./gitHubApp.key:/var/jenkins_home/gitHubApp.key
      # Monte os certificados do Kubernetes aqui, se necessário
    environment:
      CASC_JENKINS_CONFIG: /var/jenkins_home/casc_configs/jenkins.yaml
      GITHUB_APP_KEY: ${GITHUB_APP_KEY_CONTENT}
    container_name: jenkins-local

volumes:
  jenkins_home:
